"""
Enrich input images with features generated by pretrained FaceNet
"""

from gemini.features.facenet import FaceNet
import tensorflow as tf
import argparse
import sys

FLAGS = None


def main(_):

    # Import images to enrich
    images = []

    with tf.Session() as sess:

        # Load pretrained FaceNet
        facenet = FaceNet(sess=sess, model_path=FLAGS.model_path, verbose=FLAGS.print_data)



if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_path', type=str, default='models/vggface2',
                        help='Path to pretrained FaceNet model directory')
    parser.add_argument('--data_path', type=str, default='models/vggface2',
                        help='Path to image data directory')
    parser.add_argument('--print_data', action='store_true',
                        help='Print restored data')

    FLAGS, unparsed = parser.parse_known_args()
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)